### ISSUE TITLE
climate control stopped working, temperature is still available

### ISSUE THREAD

**Issue by vmpr** [andrewleech/ha_magiqtouch#29]
hi andrew, thanks for your great work!

I installed the integration a month ago and everything worked perfectly, but after two weeks it's not working anymore 😞
Interestingly, the sensor.magiqtouch_internal_temperature still works and gives temperatures back but not the entity climate.magiqtouch:

`This entity is no longer being provided by the magiqtouch integration. If the entity is no longer in use, delete it in settings.`

here is the error from the log:
```
This error originated from a custom integration.

Logger: magiqtouch
Source: custom_components/magiqtouch/magiqtouch.py:280
integration: Seeley MagIQtouch (documentation, issues)
First occurred: 12:02:13 PM (6 occurrences)
Last logged: 12:03:59 PM

wait_for_new_state
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/asyncio/tasks.py", line 520, in wait_for
    return await fut
           ^^^^^^^^^
  File "/usr/local/lib/python3.12/asyncio/queues.py", line 158, in get
    await getter
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/magiqtouch/magiqtouch.py", line 280, in wait_for_new_state
    while new_state := await asyncio.wait_for(self.state_queue.get(), timeout):
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/asyncio/tasks.py", line 519, in wait_for
    async with timeouts.timeout(timeout):
  File "/usr/local/lib/python3.12/asyncio/timeouts.py", line 115, in __aexit__
    raise TimeoutError from exc_val
TimeoutError
```

any idea what could be wrong?
cheers Ringo

**Comment by BrutalDeluxe20** [comment]
Hey @vmpr, mine is working fine.  Maybe remove the integration and re-add it, or even remove it from HACS and re-add it from scratch and see how you go? The fact you're still getting the temp reading would suggest your username/password is correct.

**Comment by andrewleech** [comment]
Mine very much does not work well, dropping out after a while is kinda the same, but to be honest mine usually doesn't work much even when first restarted.

Usability currently seems to depend on what equipment your system has running. I've only got the evap and it needs more work from me to make it stable again. Not sure when I'll have time to do that though.

**Comment by vmpr** [comment]
Thanks guys! I upgraded homeassitant yesterday from 10.4 to 11.2 and now it’s working again ;)
